#pragma once

#define BIND_GLOBAL_CAMERA 0
#define BIND_GLOBAL_SUN 1
#define BIND_GLOBAL_POINT_LIGHTS 2
#define BIND_GLOBAL_POINT_LIGHT_COUNT 3
#define BIND_GLOBAL_SH_PROBES 4
#define BIND_GLOBAL_SH_GRID_INFO 5
#define BIND_GLOBAL_GTAO_TEXTURE 6
#define BIND_GLOBAL_REFLECTION_PROBES 7
#define BIND_GLOBAL_REFLECTION_PROBE_COUNT 8

#define BIND_MODEL_PRIMITIVES 0
#define BIND_MODEL_TRANSFORMS 1
#define BIND_MODEL_INDIRECT_DRAW 2
#define BIND_MODEL_VISIBLE_INDICES 3
#define BIND_MODEL_COMPACTED_DRAW 4
#define BIND_MODEL_DRAW_COUNT 5

#define BIND_TEXTURES_ARRAY 0
#define BIND_TEXTURES_SHADOW_MAP 1
#define BIND_TEXTURES_MATERIALS 2
#define BIND_TEXTURES_CUBEMAP_SAMPLER 3
#define BIND_TEXTURES_CUBEMAP_STORAGE 4
#define BIND_TEXTURES_GI_CAPTURE_CUBEMAP 5
#define BIND_TEXTURES_PREFILTERED_MAP 6
#define BIND_TEXTURES_BRDF_LUT 7
#define BIND_TEXTURES_REFLECTION_CUBEMAPS 8

#define MAX_BINDLESS_TEXTURES 2048
#define MAX_REFLECTION_PROBES 32u
