#define BINDING_CAMERA 0
#define BINDING_SUN 1
#define BINDING_TEXTURE_ARRAY 0
#define BINDING_SHADOW_MAP 1
#define BINDING_MATERIAL_BUFFER 2
#define BINDING_CUBEMAP_SAMPLER 3
#define BINDING_CUBEMAP_STORAGE 4
#define BINDING_MODEL_DATA 0
#define BINDING_TRANSFORM_DATA 1
#define BINDING_INDIRECT_DRAW_DATA 2
#define BINDING_VISIBLE_INDICES 3

